[package]
name = "kryptopass"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
crc32fast = "1.4.2"
hmac = "0.12.1"
serde = { version = "1.0.203", features = ["derive"] }
sha2 = "0.10.8"
uuid = { version = "1.9.1", features = ["v4"] }
